#ifndef CGE_LOBBY_EVENT_ENUMS_HPP
#define CGE_LOBBY_EVENT_ENUMS_HPP
namespace cge
{
	enum ChatAreaEnum
	{
		LOBBY_CHAT,
		TABLE_CHAT,
		GAME_CHAT
	};

	enum PlayerMenuContext
	{
		CHAT_RCLICK,
		AVATAR_RCLICK,
		LIST_FRIEND_RCLICK,
		LIST_ENEMY_RCLICK,
		LIST_LOBBY_RCLICK,
		LIST_IN_GAME_RCLICK,
		AVATAR_WATCHER_RCLICK,
		AT_TABLE_RCLICK,
		CHAT_SELECT_RCLICK

	};

	enum GroupTypeEnum
	{
		FRIENDS_GROUP,
		ENEMIES_GROUP,
		IN_LOBBY_GROUP,
		IN_GAME_GROUP
	};

	enum TableTypeEnum
	{
		NOT_SET_TT,
		PASS_TWO_PARTNERSHIP_TT,
		REGULAR_PARTNERSHIP_TT,
		INDIVIDUAL_TT,
		CUT_THROAT_TT
	};

	enum TableFilterEnum
	{
		ALL_TABLES_TFILTER,
		PASS_TWO_TFILTER,
		REGULAR_TFILTER,
		INDIVIDUAL_TFILTER,
		CUT_THROAT_TFILTER,
		NORMAL_BID_TFILTER,
		MIRROR_BID_TFILTER,
		SUICIDE_BID_TFILTER,
		SCORE_TFILTER,
		TIME_TFILTER,
		HAND_TFILTER,
		SOCIAL_TABLE_TFILTER,
		RATED_TABLE_TFILTER,
		HIDE_EMPTY_TFILTER,
		HIDE_FULL_TFILTER
	};

}
#endif